# Generated by Django 3.1.4 on 2020-12-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('func_name', models.CharField(max_length=30)),
                ('inputs', models.CharField(max_length=20)),
                ('time_spent', models.FloatField()),
            ],
        ),
    ]
