# Generated by Django 3.1.4 on 2020-12-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='time_spent',
            field=models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Time Spent (ms)'),
        ),
    ]
